---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks101
  region: ap-northeast-2
  version: "1.22"

addons:
- name: vpc-cni # no version is specified so it deploys the default version
  # version: 1.12.0 # 확인필요
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: coredns
  version: latest # auto discovers the latest available
- name: kube-proxy
  version: latest
- name: aws-ebs-csi-driver
  version: latest
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
